---
title: "Tabelas"
output: html_notebook
---



row{.tabset}
--------------------------------------------------------
### Unidades com seus Agentes Comunitarios 

```{r}

final %>% 
  select(-necessidade_ajustada) %>% 
reactable(
  columns = list(
    nome_limpo_acs = colDef(name = "Unidade de Saúde",
                            minWidth = 270,
                            headerStyle = list(background = "lightblue")),
  
    nome = colDef(name = "Nome do ACS",
                  minWidth = 350),
    
    alocados = colDef(name = "Alocados",
                      minWidth = 80,
                      align = "center"),
    
    acs_necessarios = colDef(name = "Necessidade",
                      minWidth = 100,
                      align = "center"),
    
    contrato = colDef(name = "Tipo de\nContrato",
                      minWidth = 80,
                      align = "center"),
    
    admissao = colDef(name = "Admissão",
                      minWidth = 120,
                      align = "center"),
    
    
    
    
    ordem = colDef(name = "Ranking",
                      minWidth = 100,
                      align = "center"),
    
    demitir = colDef(name = "Possibilidade\nDesligamento",
                      minWidth = 120,
                      align = "center")
    
  ),
  bordered = TRUE,
  highlight = TRUE, 
  striped = TRUE,
  searchable = TRUE,
  groupBy = "nome_limpo_acs",
  defaultPageSize = 15,
  minRows = 15,
  showPageSizeOptions = TRUE
)

final %>% write.xlsx(file = "../report/final.xlsx")

final %>% 
  count(nome_limpo_acs, contrato, acs_necessarios) %>% 
  pivot_wider(names_from = contrato, values_from = n) %>% clean_names() %>% 
  mutate(
    cargos = ifelse(is.na(em51), 
                    ifelse(acs_necessarios > clt, clt, acs_necessarios),
                    ifelse(em51 > acs_necessarios, em51, acs_necessarios)
                    
    )
  ) %>% write.xlsx(file = "../report/cargos_a_criar.xlsx")


final %>% 
  count(nome_limpo_acs, contrato, acs_necessarios) %>% 
  pivot_wider(names_from = contrato, values_from = n) %>% clean_names() %>% 
  mutate(
    cargos = ifelse(is.na(em51), 
                    ifelse(acs_necessarios > clt, clt, acs_necessarios),
                    ifelse(em51 > acs_necessarios, em51, acs_necessarios)
                    
    )
  ) %>% 
  pull(cargos) %>% sum(na.rm = TRUE)

```

### Equipes sem ACS 


```{r}

demanda %>% 
  nest(no_equipe, equipe, ) %>% 
  mutate(
    vagas = map_dbl(data, nrow)
  ) %>% reactable()


```

